# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-16 14:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MAIN', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='fax',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='company',
            name='tel',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='company',
            name='website',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='person',
            name='tel',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='subsidiary',
            name='relation',
            field=models.CharField(blank=True, choices=[('', '---'), ('Adh\xe9rent', 'Adh\xe9rent'), ('Membre', 'Membre'), ('Antenne', 'Antenne'), ('Antenne internationale', 'Antenne internationale'), ('Filliale', 'Filliale'), ('Agence', 'Agence'), ('F\xe9d\xe9ration r\xe9gionale', 'F\xe9d\xe9ration r\xe9gionale'), ('Chambre syndicale', 'Chambre syndicale'), ('D\xe9l\xe9gation', 'D\xe9l\xe9gation')], max_length=255, verbose_name="nature de l'affiliation"),
        ),
        migrations.AlterField(
            model_name='subsidiary',
            name='relation_alt',
            field=models.CharField(blank=True, max_length=255, verbose_name='nature affiliation alternative'),
        ),
    ]
