# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-23 12:40
from __future__ import unicode_literals

from django.db import migrations
import mezzanine.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('MAIN', '0002_auto_20160516_1403'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'ordering': ['title'], 'verbose_name': 'MARQUE'},
        ),
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ['title'], 'verbose_name': 'SOCIETE'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['title'], 'verbose_name': 'PRODUIT'},
        ),
        migrations.AlterModelOptions(
            name='topic',
            options={'ordering': ['title'], 'verbose_name': 'RUBRIQUE'},
        ),
        migrations.AlterField(
            model_name='company',
            name='illustration',
            field=mezzanine.core.fields.FileField(blank=True, default=False, max_length=255, verbose_name='illustration'),
            preserve_default=False,
        ),
    ]
