# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-25 12:26
from __future__ import unicode_literals

from django.db import migrations
import mezzanine.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('MAIN', '0003_auto_20160523_1240'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='content',
            field=mezzanine.core.fields.RichTextField(default=False, verbose_name='Content'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='content',
            field=mezzanine.core.fields.RichTextField(default=False, verbose_name='Content'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='content',
            field=mezzanine.core.fields.RichTextField(default=False, verbose_name='Content'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='content',
            field=mezzanine.core.fields.RichTextField(default=False, verbose_name='Content'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='topic',
            name='content',
            field=mezzanine.core.fields.RichTextField(default=False, verbose_name='Content'),
            preserve_default=False,
        ),
    ]
