# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-26 12:46
from __future__ import unicode_literals

from django.db import migrations
import mezzanine.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('MAIN', '0005_auto_20160526_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='illustration',
            field=mezzanine.core.fields.FileField(blank=True, max_length=255, null=True, verbose_name='illustration'),
        ),
    ]
