# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-31 12:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MAIN', '0006_auto_20160526_1246'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='bp',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
