# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-31 14:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MAIN', '0007_company_bp'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ['title'], 'verbose_name': 'INDIVIDU'},
        ),
    ]
